# -*- coding: utf-8 -*-
"""fizz_buzz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tS_PnCQbZWK1g4-xahm-cicm6OIFvV6V

The second code block uses a loop instead of haveing to run the code every time you want to enter a number.
"""

number = int(input("Please enter a numer: "))

if number % 3 == 0 and number % 5 == 0:
    print("FizzBuzz")
elif number % 3 == 0:
    print("Fizz")
elif number % 5 == 0:
    print("Buzz")

guess = int(input("Please enter a numer: "))

while guess :
  if guess % 3 == 0 and guess % 5 == 0:
    guess = int(input("FizzBuzz! "))
  elif guess % 3 == 0:
    guess = int(input("Fizz! "))
  elif guess % 5 == 0:
    guess = int(input("Buzz! "))
  else :
    break