# -*- coding: utf-8 -*-
"""fortune_cookie.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2aSeQxMWp9l5Fe64WG3Fb4kGOD2uFFk
"""

import random

lucky_number = random.randint(1,100)

fortune_number = random.randint(1,3)

fortune_text = ''

if fortune_number == 1:
  fortune_text = 'You will have a great day!'
if fortune_number == 2:
  fortune_text = 'Today will be tough!'
if fortune_number == 3:
  fortune_text = 'You will meet the one today!'

print(f'{fortune_text} Your lucky number is: {lucky_number}')