# -*- coding: utf-8 -*-
"""lyrics_analyzer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_Wqcl-sLpk8Dxp0pYRv0yhZgweoMnb6
"""

text = """
A dozen crows and then some on the rhododendrons
In the cemetery where I lay
Like Rebecca reigning over Manderley
My foot fell upon your grave
Like a pressure point hidden beneath the soil
Down came sheets of pouring hail
I sheltered in the church's archway then
From the shards of glass falling so pale
And I looked up and saw the sun, it separated all the colors
And the ice, into my eyes, it fell and left me blind
That was the last thing that I saw, the fractured glass in its downpour
I felt the blood mix with the water and I didn't see no more
I came across an injured dove
I wanted to put her out of her misery
There came no signal from above
No sign, no guide, I thought whatever could this mean
And with my hand I picked her up
And in that moment, oh, it shifted magically
For when her feathers felt my touch, I saw her a demon
Feathers, they turned black
Oh, she was no Phoenix, but a creature of the ash
I let her go, she hit the ground
I heard the thud, regained her color
Saw the scars, she had been bound by someone and left to die
I never really found that dove
It's just a story I made up
Because I wanted all of this to stop
And I didn't know how to tell you
I didn't know how (mhm, mhm, mhm)
Oh, I didn't know how (mhm, mhm, mhm) (ooh)
And I looked up, into the sun, it separated all the colors
And the ice into my eyes, it fell and left me blind
And I looked up, and saw the sun, it separated all the colors
And the ice into my eyes, it fell and changed my mind
"""

print(text.split())

word_count = {}

for word in text.lower().split():
  if word in word_count:
    word_count[word] += 1
  else:
    word_count[word] = 1

print(word_count)