# -*- coding: utf-8 -*-
"""number_guesser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lsP5AKdgarBoJwKtDLPHMLB9JEdCAEUX
"""

import random
import time

print("Welcome to the guessing game! I'm going to pick a number between 1 and 100")
time.sleep(3)
print("Picking a number...")
time.sleep(3)

guess = int(input("What is your guess?: "))
correct_number = random.randint(1, 100)
guess_count = 1

while guess != correct_number:
  guess_count += 1
  if guess < correct_number:
    guess = int(input("Wrong. You need to guess higher. What is your guess?: "))
  else:
    guess = int(input("Wrong. You need to guess lower. What is your guess?: "))


print(f"Congrats! The right number was {correct_number}. It took you {guess_count} guesses.")